# -*- coding: utf-8 -*-
"""Emploee_Attirationproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SgjUE8nPzYFnFPmhd4KYAZoBlORYiobO
"""

import pandas as pd

from google.colab import drive
drive.mount ('/content/drive')

data = pd.read_csv("/content/drive/My Drive/Colab Notebooks/dataset/people.csv")

data.head(10)

data['dept'].value_counts()

data.columns

# summary
data.info()

# statistical

data.describe()

data.isnull().sum()

# duplicate values
data[data.duplicated()]

# removing duplicate values -- data quality,accurate insights,

data= data.drop_duplicates()

data.head(10)

data.info()

# feature extraction

visuals=['dept','numberOfProjects ','timeSpent.company','workAccident','promotionInLast5years','salary']

visuals

# plot all features vs left column

import matplotlib.pyplot as plt
import seaborn as sns

fig = plt.subplots(figsize=(10,15))
for p,q in enumerate(visuals):
  plt.subplot(3,2,p+1)
  plt.subplots_adjust(hspace=1.0)
  sns.countplot(x=q, data=data,hue='left')
  plt.xticks(rotation=90)

